Traceback (most recent call last):
  File "/Users/victormorales/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/victormorales/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/victormorales/opt/anaconda3/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/victormorales/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/victormorales/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/victormorales/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/victormorales/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ajuste1 = smf.probit('GRADE ~ GPA + TUCE + PSI',data = datos).fit()

print(ajuste1.summary())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/compat.py:36[0m, in [0;36mcall_and_wrap_exc[0;34m(msg, origin, f, *args, **kwargs)[0m
[1;32m     35[0m [38;5;28;01mtry[39;00m:
[0;32m---> 36[0m     [38;5;28;01mreturn[39;00m [43mf[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m     37[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/eval.py:169[0m, in [0;36mEvalEnvironment.eval[0;34m(self, expr, source_name, inner_namespace)[0m
[1;32m    168[0m code [38;5;241m=[39m [38;5;28mcompile[39m(expr, source_name, [38;5;124m"[39m[38;5;124meval[39m[38;5;124m"[39m, [38;5;28mself[39m[38;5;241m.[39mflags, [38;5;28;01mFalse[39;00m)
[0;32m--> 169[0m [38;5;28;01mreturn[39;00m [38;5;28;43meval[39;49m[43m([49m[43mcode[49m[43m,[49m[43m [49m[43m{[49m[43m}[49m[43m,[49m[43m [49m[43mVarLookupDict[49m[43m([49m[43m[[49m[43minner_namespace[49m[43m][49m
[1;32m    170[0m [43m                                    [49m[38;5;241;43m+[39;49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_namespaces[49m[43m)[49m[43m)[49m

File [0;32m<string>:1[0m

[0;31mNameError[0m: name 'GRADE' is not defined

The above exception was the direct cause of the following exception:

[0;31mPatsyError[0m                                Traceback (most recent call last)
Cell [0;32mIn[22], line 1[0m
[0;32m----> 1[0m ajuste1 [38;5;241m=[39m [43msmf[49m[38;5;241;43m.[39;49m[43mprobit[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mGRADE ~ GPA + TUCE + PSI[39;49m[38;5;124;43m'[39;49m[43m,[49m[43mdata[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mdatos[49m[43m)[49m[38;5;241m.[39mfit()
[1;32m      3[0m [38;5;28mprint[39m(ajuste1[38;5;241m.[39msummary())

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/statsmodels/base/model.py:203[0m, in [0;36mModel.from_formula[0;34m(cls, formula, data, subset, drop_cols, *args, **kwargs)[0m
[1;32m    200[0m [38;5;28;01mif[39;00m missing [38;5;241m==[39m [38;5;124m'[39m[38;5;124mnone[39m[38;5;124m'[39m:  [38;5;66;03m# with patsy it's drop or raise. let's raise.[39;00m
[1;32m    201[0m     missing [38;5;241m=[39m [38;5;124m'[39m[38;5;124mraise[39m[38;5;124m'[39m
[0;32m--> 203[0m tmp [38;5;241m=[39m [43mhandle_formula_data[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m,[49m[43m [49m[43mformula[49m[43m,[49m[43m [49m[43mdepth[49m[38;5;241;43m=[39;49m[43meval_env[49m[43m,[49m
[1;32m    204[0m [43m                          [49m[43mmissing[49m[38;5;241;43m=[39;49m[43mmissing[49m[43m)[49m
[1;32m    205[0m ((endog, exog), missing_idx, design_info) [38;5;241m=[39m tmp
[1;32m    206[0m max_endog [38;5;241m=[39m [38;5;28mcls[39m[38;5;241m.[39m_formula_max_endog

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/statsmodels/formula/formulatools.py:63[0m, in [0;36mhandle_formula_data[0;34m(Y, X, formula, depth, missing)[0m
[1;32m     61[0m [38;5;28;01melse[39;00m:
[1;32m     62[0m     [38;5;28;01mif[39;00m data_util[38;5;241m.[39m_is_using_pandas(Y, [38;5;28;01mNone[39;00m):
[0;32m---> 63[0m         result [38;5;241m=[39m [43mdmatrices[49m[43m([49m[43mformula[49m[43m,[49m[43m [49m[43mY[49m[43m,[49m[43m [49m[43mdepth[49m[43m,[49m[43m [49m[43mreturn_type[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mdataframe[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m     64[0m [43m                           [49m[43mNA_action[49m[38;5;241;43m=[39;49m[43mna_action[49m[43m)[49m
[1;32m     65[0m     [38;5;28;01melse[39;00m:
[1;32m     66[0m         result [38;5;241m=[39m dmatrices(formula, Y, depth, return_type[38;5;241m=[39m[38;5;124m'[39m[38;5;124mdataframe[39m[38;5;124m'[39m,
[1;32m     67[0m                            NA_action[38;5;241m=[39mna_action)

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/highlevel.py:309[0m, in [0;36mdmatrices[0;34m(formula_like, data, eval_env, NA_action, return_type)[0m
[1;32m    299[0m [38;5;250m[39m[38;5;124;03m"""Construct two design matrices given a formula_like and data.[39;00m
[1;32m    300[0m 
[1;32m    301[0m [38;5;124;03mThis function is identical to :func:`dmatrix`, except that it requires[39;00m
[0;32m   (...)[0m
[1;32m    306[0m [38;5;124;03mSee :func:`dmatrix` for details.[39;00m
[1;32m    307[0m [38;5;124;03m"""[39;00m
[1;32m    308[0m eval_env [38;5;241m=[39m EvalEnvironment[38;5;241m.[39mcapture(eval_env, reference[38;5;241m=[39m[38;5;241m1[39m)
[0;32m--> 309[0m (lhs, rhs) [38;5;241m=[39m [43m_do_highlevel_design[49m[43m([49m[43mformula_like[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43meval_env[49m[43m,[49m
[1;32m    310[0m [43m                                  [49m[43mNA_action[49m[43m,[49m[43m [49m[43mreturn_type[49m[43m)[49m
[1;32m    311[0m [38;5;28;01mif[39;00m lhs[38;5;241m.[39mshape[[38;5;241m1[39m] [38;5;241m==[39m [38;5;241m0[39m:
[1;32m    312[0m     [38;5;28;01mraise[39;00m PatsyError([38;5;124m"[39m[38;5;124mmodel is missing required outcome variables[39m[38;5;124m"[39m)

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/highlevel.py:164[0m, in [0;36m_do_highlevel_design[0;34m(formula_like, data, eval_env, NA_action, return_type)[0m
[1;32m    162[0m [38;5;28;01mdef[39;00m [38;5;21mdata_iter_maker[39m():
[1;32m    163[0m     [38;5;28;01mreturn[39;00m [38;5;28miter[39m([data])
[0;32m--> 164[0m design_infos [38;5;241m=[39m [43m_try_incr_builders[49m[43m([49m[43mformula_like[49m[43m,[49m[43m [49m[43mdata_iter_maker[49m[43m,[49m[43m [49m[43meval_env[49m[43m,[49m
[1;32m    165[0m [43m                                  [49m[43mNA_action[49m[43m)[49m
[1;32m    166[0m [38;5;28;01mif[39;00m design_infos [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    167[0m     [38;5;28;01mreturn[39;00m build_design_matrices(design_infos, data,
[1;32m    168[0m                                  NA_action[38;5;241m=[39mNA_action,
[1;32m    169[0m                                  return_type[38;5;241m=[39mreturn_type)

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/highlevel.py:66[0m, in [0;36m_try_incr_builders[0;34m(formula_like, data_iter_maker, eval_env, NA_action)[0m
[1;32m     64[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(formula_like, ModelDesc):
[1;32m     65[0m     [38;5;28;01massert[39;00m [38;5;28misinstance[39m(eval_env, EvalEnvironment)
[0;32m---> 66[0m     [38;5;28;01mreturn[39;00m [43mdesign_matrix_builders[49m[43m([49m[43m[[49m[43mformula_like[49m[38;5;241;43m.[39;49m[43mlhs_termlist[49m[43m,[49m
[1;32m     67[0m [43m                                   [49m[43mformula_like[49m[38;5;241;43m.[39;49m[43mrhs_termlist[49m[43m][49m[43m,[49m
[1;32m     68[0m [43m                                  [49m[43mdata_iter_maker[49m[43m,[49m
[1;32m     69[0m [43m                                  [49m[43meval_env[49m[43m,[49m
[1;32m     70[0m [43m                                  [49m[43mNA_action[49m[43m)[49m
[1;32m     71[0m [38;5;28;01melse[39;00m:
[1;32m     72[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/build.py:693[0m, in [0;36mdesign_matrix_builders[0;34m(termlists, data_iter_maker, eval_env, NA_action)[0m
[1;32m    689[0m factor_states [38;5;241m=[39m _factors_memorize(all_factors, data_iter_maker, eval_env)
[1;32m    690[0m [38;5;66;03m# Now all the factors have working eval methods, so we can evaluate them[39;00m
[1;32m    691[0m [38;5;66;03m# on some data to find out what type of data they return.[39;00m
[1;32m    692[0m (num_column_counts,
[0;32m--> 693[0m  cat_levels_contrasts) [38;5;241m=[39m [43m_examine_factor_types[49m[43m([49m[43mall_factors[49m[43m,[49m
[1;32m    694[0m [43m                                               [49m[43mfactor_states[49m[43m,[49m
[1;32m    695[0m [43m                                               [49m[43mdata_iter_maker[49m[43m,[49m
[1;32m    696[0m [43m                                               [49m[43mNA_action[49m[43m)[49m
[1;32m    697[0m [38;5;66;03m# Now we need the factor infos, which encapsulate the knowledge of[39;00m
[1;32m    698[0m [38;5;66;03m# how to turn any given factor into a chunk of data:[39;00m
[1;32m    699[0m factor_infos [38;5;241m=[39m {}

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/build.py:443[0m, in [0;36m_examine_factor_types[0;34m(factors, factor_states, data_iter_maker, NA_action)[0m
[1;32m    441[0m [38;5;28;01mfor[39;00m data [38;5;129;01min[39;00m data_iter_maker():
[1;32m    442[0m     [38;5;28;01mfor[39;00m factor [38;5;129;01min[39;00m [38;5;28mlist[39m(examine_needed):
[0;32m--> 443[0m         value [38;5;241m=[39m [43mfactor[49m[38;5;241;43m.[39;49m[43meval[49m[43m([49m[43mfactor_states[49m[43m[[49m[43mfactor[49m[43m][49m[43m,[49m[43m [49m[43mdata[49m[43m)[49m
[1;32m    444[0m         [38;5;28;01mif[39;00m factor [38;5;129;01min[39;00m cat_sniffers [38;5;129;01mor[39;00m guess_categorical(value):
[1;32m    445[0m             [38;5;28;01mif[39;00m factor [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m cat_sniffers:

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/eval.py:568[0m, in [0;36mEvalFactor.eval[0;34m(self, memorize_state, data)[0m
[1;32m    567[0m [38;5;28;01mdef[39;00m [38;5;21meval[39m([38;5;28mself[39m, memorize_state, data):
[0;32m--> 568[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_eval[49m[43m([49m[43mmemorize_state[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43meval_code[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m
[1;32m    569[0m [43m                      [49m[43mmemorize_state[49m[43m,[49m
[1;32m    570[0m [43m                      [49m[43mdata[49m[43m)[49m

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/eval.py:551[0m, in [0;36mEvalFactor._eval[0;34m(self, code, memorize_state, data)[0m
[1;32m    549[0m [38;5;28;01mdef[39;00m [38;5;21m_eval[39m([38;5;28mself[39m, code, memorize_state, data):
[1;32m    550[0m     inner_namespace [38;5;241m=[39m VarLookupDict([data, memorize_state[[38;5;124m"[39m[38;5;124mtransforms[39m[38;5;124m"[39m]])
[0;32m--> 551[0m     [38;5;28;01mreturn[39;00m [43mcall_and_wrap_exc[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mError evaluating factor[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m    552[0m [43m                             [49m[38;5;28;43mself[39;49m[43m,[49m
[1;32m    553[0m [43m                             [49m[43mmemorize_state[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43meval_env[39;49m[38;5;124;43m"[39;49m[43m][49m[38;5;241;43m.[39;49m[43meval[49m[43m,[49m
[1;32m    554[0m [43m                             [49m[43mcode[49m[43m,[49m
[1;32m    555[0m [43m                             [49m[43minner_namespace[49m[38;5;241;43m=[39;49m[43minner_namespace[49m[43m)[49m

File [0;32m~/opt/anaconda3/lib/python3.9/site-packages/patsy/compat.py:43[0m, in [0;36mcall_and_wrap_exc[0;34m(msg, origin, f, *args, **kwargs)[0m
[1;32m     39[0m     new_exc [38;5;241m=[39m PatsyError([38;5;124m"[39m[38;5;132;01m%s[39;00m[38;5;124m: [39m[38;5;132;01m%s[39;00m[38;5;124m: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m
[1;32m     40[0m                          [38;5;241m%[39m (msg, e[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m, e),
[1;32m     41[0m                          origin)
[1;32m     42[0m     [38;5;66;03m# Use 'exec' to hide this syntax from the Python 2 parser:[39;00m
[0;32m---> 43[0m     [43mexec[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mraise new_exc from e[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m     44[0m [38;5;28;01melse[39;00m:
[1;32m     45[0m     [38;5;66;03m# In python 2, we just let the original exception escape -- better[39;00m
[1;32m     46[0m     [38;5;66;03m# than destroying the traceback. But if it's a PatsyError, we can[39;00m
[1;32m     47[0m     [38;5;66;03m# at least set the origin properly.[39;00m
[1;32m     48[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(e, PatsyError):

File [0;32m<string>:1[0m

[0;31mPatsyError[0m: Error evaluating factor: NameError: name 'GRADE' is not defined
    GRADE ~ GPA + TUCE + PSI
    ^^^^^

